### ISSUE TITLE
Avg vote time calculations

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#471] opened 2018-05-17 22:14 UTC
Avg vote time calculation being used is currently based on ticket pool param. On mainnet 8192 blocks is what is used and arrives at 28.44 days, but average vote time probability calculations comes to 8102 blocks which is 28.13 days. Needs to be resolved on home page ROI calculation as well as the APR pull request. https://github.com/decred/dcrdata/pull/468

This can also be worked into an improved version of the luck calculation, probably as a separate PR.

**Comment by davecgh** [comment] 2018-05-18 01:10
For reference, that should be 7860, not 8102.  There was a typo in the formula.

Since the probability formula is:

![image](https://user-images.githubusercontent.com/2115102/40152038-183fb2dc-5949-11e8-9b08-44795918eda3.png)

The EV is:

http://www.wolframalpha.com/input/?i=sum+B*8191%5E(B-1)+%2F+8192%5EB,+B%3D1+to+40960

This is confirmed by calculating the statistics from the chain across all tickets since the beginning with [dcrvotetimes](https://github.com/davecgh/dcrvotetimes):

```
Calculating average vote time through block height 239700...
Height..1000..2000..3000..4000..5000..6000..7000..8000..9000
...
..230000..231000..232000..233000..234000..235000..236000..237000..238000..239000..done
Mean wait for 1156623 votes: 7859.5 blocks, 27.23 days
```

**Comment by papacarp** [comment] 2018-06-05 21:14
@davecgh  any recommendations on how to code this into GO so we can derive from params rather than hard code 7860?  I tried a for loop sum, but end up with overflows rather quickly.  Looked briefly for internet references to go and summations - NL.

**Comment by chappjc** [comment] 2018-06-05 22:51
It's not too bad if you apply a log to the equation:

```
a = 8191, b = 8192
fn(x) = log(x) + (x-1)*log(a) - x*log(b)
E = sum(exp(fn(x)), x=1 to 40960)
```

7860.917491203549

**Comment by chappjc** [comment] 2018-06-05 23:06
[Playground](https://play.golang.org/p/_GIlQbF9rTx)

Prints 7860.917491184401

**Comment by davecgh** [comment] 2018-06-06 09:58
I still suspect that asserting things haven't changed and just using constants for the values along with comments how they were derived is probably a good idea since there are certainly a lot of other assumptions made accordingly, but it can certainly be estimated via logs as @chappjc pointed out.

If you want to go that route, you can simplify it further by knowing that the target pool size is always the number of tickets per block times the defined ticket pool size.  The result is that the CDF will reduce to `sum( (poolSize - 1)^(B-1) / poolSize^B` and consequently the code to calculate it via logs would be:

```Go
package main

import (
	"fmt"
	"math"

	"github.com/decred/dcrd/chaincfg"
)

func calcMeanVotingBlocks(params *chaincfg.Params) int64 {
	poolSize := float64(params.TicketPoolSize)
	var v float64
	for i := float64(1); i <= float64(params.TicketExpiry); i++ {
		v += math.Exp(math.Log(i) + (i-1)*math.Log(poolSize-1) - i*math.Log(poolSize))
	}
	return int64(v)
}

func main() {
	fmt.Println("mainnet", calcMeanVotingBlocks(&chaincfg.MainNetParams))
	fmt.Println("testnet2", calcMeanVotingBlocks(&chaincfg.TestNet2Params))
}
```

Output:
```
mainnet: 7860
testnet2: 1006
```

**Comment by papacarp** [comment] 2018-06-06 17:37
Thank you.  This is exactly what I needed.   I spoke with @raedah and we are going to put in a variation the calculated version you both came up with.

**Comment by chappjc** [comment] 2018-06-30 00:18
resolved by PR https://github.com/decred/dcrdata/pull/468, specifically `explorer.calcMeanVotingBlocks`

**Closed by chappjc** 2018-06-30 00:18 UTC
