### ISSUE TITLE
Need incremental handling of charts data

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdata#1034] opened 2019-02-19 22:47 UTC
`pgblockchain.GetPgChartsData` is used to pull all charts data from the database every time a block is received, which takes a long time. Most if not all of those datasets should be maintained incrementally, probably with their own `BlockDataSaver` as well as some reorg handling. 

Optionally, rather than use `dbtypes.ChartsData` for everything, we may want to create custom types for each dataset and have the `BlockDataSaver` create JSON-formatted byte arrays for faster retrieval. 

`GetPgChartsData` can still be called once on startup to initially populate the datasets.

**Comment by dmigwi** [comment] 2019-02-23 17:10
This is a very valid point you raise. The explorer calls `pgblockchain.GetPgChartsData` method at intervals 5 blocks when then not running blockchain sync. After updating the charts data there are charts that are rarely accessed thus there is data that lay idle in the cache waiting to be used which may not happen for a while.
We could fix this slow charts data cache update by letting the user to trigger updates to a specific chart's cache data if it is invalid. The data in the cache could be held for a couple of blocks till its considered invalid. 
We only need to ensure that multiple requests do not simultaneously try to update the invalid cache data. With this we shall have less cached data and the prescheduled slow cache updates would be gone.

**Comment by dmigwi** [comment] 2019-02-23 17:14
On second thought we may not end up having less cached data but the slow cache update will be gone.

**Comment by chappjc** [comment] 2019-02-24 14:57
The problem is that these queries are just very slow.  Letting the user trigger them does not really solve that.  @buck54321 is pointing out that in 5 blocks, very little about the cached data has changed, so why do we have to query for it all again?  Hist suggestion of hooking into block data collector's new block storage would allow an incremental change to the cached charts data.

However, I think a simpler solution is simply to query for the new data.  Say a particular charts data includes blocks N to M, where M was the best block at one point.  When a new block comes, the query required to make the charts data current is just the data for block M+1. So that data point is appended to the cached data and block N is popped from the cached data, leaving the new cached data representing N+1 to M+1.

Making this work requires a minor amount of book keeping in the charts data cache that says what blocks it represents.

Going further, the annoying startup queries that choke dcrdata for several minutes on a slow VPS can be avoided by having dcrdata save the charts data cache as a .gob on shutdown and load it on startup.  Then startup just needs to query for the new/changed data and update the cache as I've described.  If the gob is missing or corrupt, oh well, load it all.

@buck54321 and @dmigwi have you started any work on this?  I'd like to demo the idea.  Of course we can work on alternative solutions too.

**Comment by buck54321** [comment] 2019-02-24 15:03
That sounds great. Go to town.

**Comment by dmigwi** [comment] 2019-02-24 17:45
I like the new description. If @buck54321 hasn't started work on this, I would gladly like to work on it.

**Comment by chappjc** [comment] 2019-03-18 23:54
Moving to 4.1 milestone given the size of the solution.  4.1 will come fairly quickly after 4.0 though.

**Closed** 2019-04-01 13:36 UTC
