### ISSUE TITLE
data race

### ISSUE THREAD

**Issue by dajohi** [decred/dcrdata#1067] opened 2019-03-01 20:03 UTC
running on commit e53135c2271b0b1f1cd85988cf6a14d759546e6f

```
2019-03-01 19:02:57.444 [INF] PSQL: Pre-fetching project fund data at height 141767...
2019-03-01 19:03:20.561 [INF] PSQL: Avg. speed: 0 tx/s, 0 vout/s                                                    
2019-03-01 19:03:20.567 [INF] PSQL: Finding and removing duplicate vins entries...                                  
2019-03-01 19:03:40.119 [INF] PSQL: Removed 0 duplicate vins entries.                                               
2019-03-01 19:03:40.123 [INF] PSQL: Finding and removing duplicate vouts entries...                                 
2019-03-01 19:04:17.294 [INF] PSQL: Removed 0 duplicate vouts entries.                                              
2019-03-01 19:04:17.300 [INF] PSQL: Finding and removing duplicate transactions entries...
2019-03-01 19:04:29.021 [INF] PSQL: Removed 0 duplicate transactions entries.                                       
2019-03-01 19:04:29.022 [INF] PSQL: Indexing blocks table on hash...                                                
2019-03-01 19:04:30.630 [INF] PSQL: Indexing blocks table on height...                                              
2019-03-01 19:04:30.771 [INF] PSQL: Indexing transactions table on tx/block hashes...                               
2019-03-01 19:04:43.663 [INF] PSQL: Indexing transactions table on block id/indx...                                 
2019-03-01 19:04:56.079 [INF] PSQL: Indexing vins table on txin...                                                  
2019-03-01 19:05:17.374 [INF] PSQL: Indexing vins table on prevouts...                                              
2019-03-01 19:05:38.698 [INF] PSQL: Indexing vouts table on tx hash and index...
2019-03-01 19:06:11.918 [INF] PSQL: Indexing votes table on candidate block...                                      
2019-03-01 19:06:16.193 [INF] PSQL: Indexing votes table on block hash...                                           
2019-03-01 19:06:19.696 [INF] PSQL: Indexing votes table on block+tx hash...                                        
2019-03-01 19:06:23.019 [INF] PSQL: Indexing votes table on vote version...                                         
2019-03-01 19:06:23.400 [INF] PSQL: Indexing votes table on height...                                               
2019-03-01 19:06:23.882 [INF] PSQL: Indexing votes table on Block Time...                                           
2019-03-01 19:06:24.362 [INF] PSQL: Indexing misses table...                                                        
2019-03-01 19:06:24.425 [INF] PSQL: Indexing agendas table on Agenda ID...                                          
2019-03-01 19:06:24.438 [INF] DATD: PostgreSQL sync ended at height 141767                                          
2019-03-01 19:06:24.439 [ERR] DATD: dcrpg.SyncChainDBAsync failed at height 141767.
==================                                                                                                  
WARNING: DATA RACE                                                                                                   
Write at 0x00c0004df1c0 by main goroutine:                                                                          
  main._main()                                                                                                       
      /home/dcrdata/git/dcrdata/main.go:821 +0x438d                                                                 
  main._main()                                                                                                      
      /home/dcrdata/git/dcrdata/main.go:187 +0xcaa0                                                                 
  fmt.Fscanf()                                                                                                      
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf                                                                    
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()                                                       
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193                                                                   
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()               
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3      
  fmt.Fscanf()                                                                                                      
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf                                                                     
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()                                                       
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193                                                                   
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()                                                
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3
  github.com/btcsuite/goleveldb/leveldb.(*DB).checkAndCleanFiles()                                                  
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db_util.go:52 +0x2e1          
  github.com/btcsuite/goleveldb/leveldb.openDB()                                                                    
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db.go:130 +0x9f3                         
  fmt.(*ss).doScanf()                                                                                               
      /home/dcrdata/go/src/fmt/scan.go:1193 +0x377                                                                  
  fmt.Fscanf()                                                                                                       
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf                                                                    
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()                                                       
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193                                                                   
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()                                               
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3      
  fmt.Fscanf()                                                                                                      
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf                                                                    
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()                                                       
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193                                                                   
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()                                               
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3      
  fmt.Fscanf()                                                                                                      
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf                                                                    
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()                                        
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193                                                                   
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()              
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3      
  fmt.Fscanf()                                                                       
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf                                                                    
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()                         
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193                                                                   
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()                 
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3      
  fmt.Fscanf()                                                                                                      
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf                                                                    
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()                                                       
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193                                                                   
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()                     
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3      
  github.com/btcsuite/goleveldb/leveldb.(*DB).recoverJournal()                                                      
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db.go:476 +0xc5                         
  github.com/btcsuite/goleveldb/leveldb.openDB()                                                                    
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db.go:125 +0x9cf                        
  github.com/btcsuite/goleveldb/leveldb.Open()                                                                      
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db.go:197 +0x1e9                        
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()                   
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193                                                                   
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).GetMeta.func1()                                      
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:666 +0x408      
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).GetMeta.func2()                                      
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:356 +0xcc       
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).GetMeta()                                            
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:407 +0x741      
  github.com/btcsuite/goleveldb/leveldb.(*session).recover()                                                        
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/session.go:119 +0xde                    
  github.com/btcsuite/goleveldb/leveldb.Open()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db.go:183 +0xd7                 [70/1883]
  github.com/btcsuite/goleveldb/leveldb.OpenFile()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db.go:219 +0xa6
  github.com/decred/dcrd/database/ffldb.openDB()
      /home/dcrdata/go/pkg/mod/github.com/decred/dcrd/database@v1.0.3/ffldb/db.go:2068 +0x18b
  github.com/decred/dcrd/database/ffldb.openDBDriver()
      /home/dcrdata/go/pkg/mod/github.com/decred/dcrd/database@v1.0.3/ffldb/driver.go:53 +0xf7
  github.com/decred/dcrd/database.Open()
      /home/dcrdata/go/pkg/mod/github.com/decred/dcrd/database@v1.0.3/driver.go:89 +0x102
  github.com/decred/dcrdata/v4/stakedb.(*StakeDatabase).Open()
      /home/dcrdata/git/dcrdata/stakedb/stakedb.go:737 +0x1d1
  github.com/decred/dcrdata/v4/stakedb.NewStakeDatabase()
      /home/dcrdata/git/dcrdata/stakedb/stakedb.go:264 +0xa74
  github.com/decred/dcrdata/v4/db/dcrsqlite.newWiredDB()
      /home/dcrdata/git/dcrdata/db/dcrsqlite/apisource.go:62 +0x271
  github.com/decred/dcrdata/v4/db/dcrsqlite.InitWiredDB()
      /home/dcrdata/git/dcrdata/db/dcrsqlite/apisource.go:107 +0xb1
  main._main()
      /home/dcrdata/git/dcrdata/main.go:151 +0x156f
  main.main()
      /home/dcrdata/git/dcrdata/main.go:56 +0x9f

Previous write at 0x00c0004df1c0 by goroutine 352:
  ??()
      -:0 +0xffffffffffffffff
  encoding/json.(*decodeState).object()
      /home/dcrdata/go/src/encoding/json/decode.go:666 +0xe6e
  encoding/json.(*decodeState).value()
      /home/dcrdata/go/src/encoding/json/decode.go:381 +0xb0
  encoding/json.(*decodeState).unmarshal()
      /home/dcrdata/go/src/encoding/json/decode.go:179 +0x26a
  encoding/json.Unmarshal()
      /home/dcrdata/go/src/encoding/json/decode.go:106 +0x1e1
  github.com/decred/dcrdata/v4/gov/politeia/piclient.RetrieveAllProposals()
      /home/dcrdata/git/dcrdata/gov/politeia/piclient/piclient.go:58 +0x16d
  github.com/decred/dcrdata/v4/gov/politeia.(*ProposalDB).saveProposals()
      /home/dcrdata/git/dcrdata/gov/politeia/proposals.go:97 +0x1f9
  github.com/decred/dcrdata/v4/gov/politeia.(*ProposalDB).CheckProposalsUpdates()
      /home/dcrdata/git/dcrdata/gov/politeia/proposals.go:219 +0x29d
  main._main.func4()
      /home/dcrdata/git/dcrdata/main.go:533 +0x3c

Goroutine 352 (finished) created at:                                                       
  main._main()                                  
      /home/dcrdata/git/dcrdata/main.go:532 +0x292d                                          
  main._main()                                        
      /home/dcrdata/git/dcrdata/main.go:187 +0xcaa0                                           
  fmt.Fscanf()                                               
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf                                         
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()        
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193                                                             
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3
  fmt.Fscanf()                                               
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf                   
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()        
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193                                                             
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3
  github.com/btcsuite/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db_util.go:52 +0x2e1
  github.com/btcsuite/goleveldb/leveldb.openDB()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db.go:130 +0x9f3
  fmt.(*ss).doScanf()                                      
      /home/dcrdata/go/src/fmt/scan.go:1193 +0x377                                       
  fmt.Fscanf()                                                                     
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf                        
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()             
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193                                                             
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3
  fmt.Fscanf()                                               
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3
  fmt.Fscanf()
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3
  fmt.Fscanf()
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3
  fmt.Fscanf()
      /home/dcrdata/go/src/fmt/scan.go:143 +0xcf
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).List()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:458 +0x2b3
  github.com/btcsuite/goleveldb/leveldb.(*DB).recoverJournal()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db.go:476 +0xc5
  github.com/btcsuite/goleveldb/leveldb.openDB()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db.go:125 +0x9cf
  github.com/btcsuite/goleveldb/leveldb.Open()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db.go:197 +0x1e9
  github.com/btcsuite/goleveldb/leveldb/storage.fsParseName()
      /home/dcrdata/go/src/fmt/scan.go:114 +0x193
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).GetMeta.func1()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:666 +0x408
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).GetMeta.func2()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:356 +0xcc
  github.com/btcsuite/goleveldb/leveldb/storage.(*fileStorage).GetMeta()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/storage/file_storage.go:407 +0x741
  github.com/btcsuite/goleveldb/leveldb.(*session).recover()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/session.go:119 +0xde
  github.com/btcsuite/goleveldb/leveldb.Open()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db.go:183 +0xd7
  github.com/btcsuite/goleveldb/leveldb.OpenFile()
      /home/dcrdata/go/pkg/mod/github.com/btcsuite/goleveldb@v1.0.0/leveldb/db.go:219 +0xa6
  github.com/decred/dcrd/database/ffldb.openDB()
      /home/dcrdata/go/pkg/mod/github.com/decred/dcrd/database@v1.0.3/ffldb/db.go:2068 +0x18b
  github.com/decred/dcrd/database/ffldb.openDBDriver()
      /home/dcrdata/go/pkg/mod/github.com/decred/dcrd/database@v1.0.3/ffldb/driver.go:53 +0xf7
  github.com/decred/dcrd/database.Open()
      /home/dcrdata/go/pkg/mod/github.com/decred/dcrd/database@v1.0.3/driver.go:89 +0x102
  github.com/decred/dcrdata/v4/stakedb.(*StakeDatabase).Open()
      /home/dcrdata/git/dcrdata/stakedb/stakedb.go:737 +0x1d1
  github.com/decred/dcrdata/v4/stakedb.NewStakeDatabase()
      /home/dcrdata/git/dcrdata/stakedb/stakedb.go:264 +0xa74
  github.com/decred/dcrdata/v4/db/dcrsqlite.newWiredDB()
      /home/dcrdata/git/dcrdata/db/dcrsqlite/apisource.go:62 +0x271
  github.com/decred/dcrdata/v4/db/dcrsqlite.InitWiredDB()
      /home/dcrdata/git/dcrdata/db/dcrsqlite/apisource.go:107 +0xb1
  main._main()
      /home/dcrdata/git/dcrdata/main.go:151 +0x156f
  main.main()
      /home/dcrdata/git/dcrdata/main.go:56 +0x9f
==================
2019-03-01 19:06:24.469 [INF] PUBS: Stopping websocket hub.
2019-03-01 19:06:24.470 [INF] EXPR: Stopping websocket hub.
2019-03-01 19:06:24.474 [ERR] EXPR: close channel already closed. This should not happen.
2019-03-01 19:06:24.475 [ERR] EXPR: Do not send on stopPing channel, only close it.
2019-03-01 19:06:24.481 [INF] DATD: Shutdown requested. Shutting down...
2019-03-01 19:06:24.484 [INF] DATD: Gracefully shutting down web server...
2019-03-01 19:06:26.331 [INF] DATD: Closing connection to dcrd.
2019-03-01 19:06:26.335 [INF] DATD: Bye!
2019-03-01 19:06:26.586 [ERR] DATD: IndexAll failed: pq: could not create unique index "uix_agendas_name"
```

**Comment by chappjc** [comment] 2019-03-01 20:17
@dmigwi Looks like launching the Politeia update in a goroutine (probably the captured `err` value) is the issue here.  I can't reproduce this race, but I think that's it.

**Comment by chappjc** [comment] 2019-03-01 20:23
That's a crazy trace, but the problem is this:

Line 533, which is the politeia update, is conflicting with the write at 151, which is the start of the WiredDB constructor.

Notice that the Pi update is in a goroutine, and the closure has the captured err. They both are writing to the error -> data race.

Change line 533 to `if err := proposalsInstance.CheckProposa...` (note the added colon: `:=`).

That way it's shaddowing the other err instead of capturing (and trying to write to it)

**Comment by dmigwi** [comment] 2019-03-01 20:33
Sure this is a crazy trace. I couldn't understand why `fmt.Fscanf` was bieng referenced all through in the stacktrace but `:=` makes sense.

**Comment by chappjc** [comment] 2019-03-01 20:34
Might be wrong, but I think it's showing all the crap up the stack that essentially just passes the error down to main

**Comment by dmigwi** [comment] 2019-03-01 20:36
Is there a specific way to trigger the data race again?

**Comment by dmigwi** [comment] 2019-03-01 20:37
I can't seem to recreate it by adding `-race` flag to the build command.

**Comment by dmigwi** [comment] 2019-03-01 20:51
I think there maybe more to the issue than meets the eyes. I just forced an error to be returned without `:=` set and the data race did not happen. Although that could be one of the minor causes.

**Comment by chappjc** [comment] 2019-03-01 20:52
I think it was lucky timing

**Comment by dmigwi** [comment] 2019-03-01 21:00
The http client might also waited for too long.

**Comment by chappjc** [comment] 2019-03-12 22:32
Resolved by https://github.com/decred/dcrdata/pull/1068

**Closed by chappjc** 2019-03-12 22:32 UTC
