### ISSUE TITLE
Front page dev fund balance goes to 0 on websocket refresh

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#373] opened 2018-03-01 05:37 UTC

**Comment by chappjc** [comment] 2018-03-01 07:02
Indeed, although I described it much less succinctly.

https://github.com/decred/dcrdata/issues/348

**Comment by mikefullman** [comment] 2018-05-03 16:17
Just dropping this info here because I need to come back to this later.

The data from the websocket update has dev_fund = 0

> Received newblock message {"block":{"height":235487,"size":5980,"valid":false,"votes":5,"tx":3,"tickets":8,"revocations":0,"time":1525362808,"formatted_time":"2018-05-03 15:53:28","formatted_bytes":"6.0 kB"},"extra":{"coin_supply":766403701994539,"sdiff":87.58268129,"window_idx":48,"reward_idx":2015,"difficulty":325473380.9549447,**"dev_fund":0,**"dev_address":"Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx","roi":1.4642569753644041,"roi_period":"28.44 days","subsidy":{"total":2137392543,"pow":1282435529,"pos":641217760,"dev":213739254},"params":{"window_size":144,"reward_window_size":6144,"target_pool_size":0,"target_block_time":300000000000},"pool_info":{"size":40860,"value":3543347.75147725,"valavg":86.71923033473446,"percent":46.23343731581425,"target":40960,"percent_target":99.755859375}}}

It looks like we have a race condition since the call the "update dev fund" is asynchronous
https://github.com/decred/dcrdata/blob/d3288e7ea631f3ad9fdadaec9005530f8083c435/explorer/explorer.go#L280-L290

A simple solution may be to add DevFund to the ExtraInfo initialization so it maintains whatever the last value was in there until the async call updates.  dev fund will be one block behind, but I think that is preferable to holding up the page rendering for an async call.

```go
exp.ExtraInfo = &HomeInfo{
		CoinSupply:        blockData.ExtraInfo.CoinSupply,
		StakeDiff:         blockData.CurrentStakeDiff.CurrentStakeDifficulty,
		IdxBlockInWindow:  blockData.IdxBlockInWindow,
		IdxInRewardWindow: int(newBlockData.Height % exp.ChainParams.SubsidyReductionInterval),
		DevAddress:        exp.ExtraInfo.DevAddress,
->		DevFund:           exp.ExtraInfo.DevFund,
		Difficulty:        blockData.Header.Difficulty,```

**Comment by mikefullman** [comment] 2018-05-04 16:54
just fyi, I confirmed that the small change I offered "works".   Your solution would strategically be better and more accurate or I could do a simple PR now.  I'm focused on the INSIGHT API stuff now as per @raedah so won't be able to get many cycles on a new event strategy for a bit but happy to loop back to it eventually if you want.

**Comment by chappjc** [comment] 2018-05-04 17:00
Works is better than broken for now.  Please put up a PR for the patch and we'll get it in straight away.  Thanks!

**Comment by chappjc** [comment] 2018-06-30 00:14
resolved by PR https://github.com/decred/dcrdata/pull/461

**Closed by chappjc** 2018-06-30 00:14 UTC
Labels: bug
